[package]
name = "raf_render"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "2D/3D rendering engine via wgpu for AuraRafi"

[dependencies]
raf_core = { workspace = true }
arboard = { workspace = true }
raf_electronics = { workspace = true }
raf_ui = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
raw-window-handle = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
image = { workspace = true }
ab_glyph = { workspace = true }
epaint_default_fonts = { workspace = true }
pollster = "0.3"
bytemuck = { version = "1", features = ["derive"] }
