//! Schematic export functionality.
//!
//! Exports schematics to various formats: text netlist, BOM (CSV),
//! and SVG vector image. PCB/Gerber export is planned for a future
//! phase when PCB layout view is implemented.
//!
//! Technology based on Yoll AU - yoll.site

use crate::netlist::Netlist;
use crate::schematic::Schematic;
use std::collections::HashMap;

/// Available export formats.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportFormat {
    /// Text netlist: human-readable list of nets and connections.
    NetlistText,
    /// CSV Bill of Materials.
    BomCsv,
    /// SVG vector image of the schematic.
    Svg,
    /// Gerber files for JLCPCB manufacturing.
    /// Requires PCB layout (3D view) - structural placeholder.
    GerberJlcpcb,
    /// Gerber files for PCBWay manufacturing.
    /// Requires PCB layout (3D view) - structural placeholder.
    GerberPcbWay,
}

/// Export result with format-specific content.
#[derive(Debug, Clone)]
pub struct ExportResult {
    pub format: ExportFormat,
    /// The exported content as a string.
    pub content: String,
    /// Suggested file extension.
    pub extension: String,
}

/// Export a schematic as a text netlist.
pub fn export_netlist_text(schematic: &Schematic) -> ExportResult {
    let netlist = Netlist::from_schematic(schematic);
    let mut out = String::new();

    out.push_str("* Netlist generated by AuraRafi\n");
    out.push_str(&format!("* Schematic: {}\n", schematic.name));
    out.push_str(&format!("* Components: {}\n", schematic.components.len()));
    out.push_str(&format!("* Nets: {}\n", netlist.nets.len()));
    out.push_str("*\n\n");

    // Components section.
    out.push_str(".COMPONENTS\n");
    for comp in &schematic.components {
        out.push_str(&format!(
            "  {} {} {} ({})\n",
            comp.designator, comp.value, comp.footprint, comp.category
        ));
    }
    out.push('\n');

    // Nets section.
    out.push_str(".NETS\n");
    for net in &netlist.nets {
        out.push_str(&format!("  {} :\n", net.name));
        for &(ci, pi) in &net.pins {
            if ci < schematic.components.len() {
                let comp = &schematic.components[ci];
                if pi < comp.pins.len() {
                    out.push_str(&format!(
                        "    {}.{}\n",
                        comp.designator, comp.pins[pi].name
                    ));
                }
            }
        }
    }
    out.push_str("\n.END\n");

    ExportResult {
        format: ExportFormat::NetlistText,
        content: out,
        extension: "net".to_string(),
    }
}

/// Export a schematic as a CSV Bill of Materials.
pub fn export_bom_csv(schematic: &Schematic) -> ExportResult {
    let mut out = String::new();
    out.push_str("Designator,Value,Footprint,Category,Quantity\n");

    // Group components by value+footprint for quantity counting.
    let mut groups: HashMap<String, (String, String, String, usize)> = HashMap::new();

    for comp in &schematic.components {
        let key = format!("{}|{}|{}", comp.value, comp.footprint, comp.category);
        let entry = groups.entry(key).or_insert_with(|| {
            (
                comp.value.clone(),
                comp.footprint.clone(),
                comp.category.clone(),
                0,
            )
        });
        entry.3 += 1;
    }

    // Also list individual designators.
    // First, collect per-group designators.
    let mut group_designators: HashMap<String, Vec<String>> = HashMap::new();
    for comp in &schematic.components {
        let key = format!("{}|{}|{}", comp.value, comp.footprint, comp.category);
        group_designators
            .entry(key)
            .or_default()
            .push(comp.designator.clone());
    }

    let mut sorted_keys: Vec<String> = groups.keys().cloned().collect();
    sorted_keys.sort();

    for key in &sorted_keys {
        if let Some((value, footprint, category, qty)) = groups.get(key) {
            let designators = group_designators
                .get(key)
                .map(|d| d.join(" "))
                .unwrap_or_default();
            // Escape CSV values that might contain commas.
            let safe_value = if value.contains(',') {
                format!("\"{}\"", value)
            } else {
                value.clone()
            };
            out.push_str(&format!(
                "{},{},{},{},{}\n",
                designators, safe_value, footprint, category, qty
            ));
        }
    }

    ExportResult {
        format: ExportFormat::BomCsv,
        content: out,
        extension: "csv".to_string(),
    }
}

/// Export a schematic as an SVG vector image.
pub fn export_svg(schematic: &Schematic) -> ExportResult {
    let grid_step = 20.0f32;
    let comp_w = 60.0f32;
    let comp_h = 30.0f32;
    let padding = 80.0f32;

    // Calculate bounding box.
    let (min_x, min_y, max_x, max_y) = calculate_bounds(schematic, grid_step, comp_w, comp_h);
    let width = (max_x - min_x + padding * 2.0) as i32;
    let height = (max_y - min_y + padding * 2.0) as i32;
    let offset_x = -min_x + padding;
    let offset_y = -min_y + padding;

    let mut svg = String::new();
    svg.push_str(&format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{}\" height=\"{}\" viewBox=\"0 0 {} {}\">\n",
        width, height, width, height
    ));
    svg.push_str("<style>\n");
    svg.push_str("  .comp-body { fill: #23232d; stroke: #50505c; stroke-width: 1.5; }\n");
    svg.push_str("  .comp-text { font-family: monospace; font-size: 10px; fill: #c8c8d2; }\n");
    svg.push_str("  .desig-text { font-family: monospace; font-size: 10px; fill: #d4771a; }\n");
    svg.push_str("  .wire { stroke: #3cc83c; stroke-width: 2; fill: none; }\n");
    svg.push_str("  .pin { r: 3; }\n");
    svg.push_str("  .pin-line { stroke-width: 1.5; fill: none; }\n");
    svg.push_str("  .net-label { font-family: monospace; font-size: 9px; fill: #64dc64; }\n");
    svg.push_str("  .bg { fill: #121218; }\n");
    svg.push_str("</style>\n");

    // Background.
    svg.push_str(&format!(
        "<rect class=\"bg\" width=\"{}\" height=\"{}\" />\n",
        width, height
    ));

    // Draw wires.
    for wire in &schematic.wires {
        let x1 = wire.start.x + offset_x;
        let y1 = wire.start.y + offset_y;
        let x2 = wire.end.x + offset_x;
        let y2 = wire.end.y + offset_y;
        svg.push_str(&format!(
            "<line class=\"wire\" x1=\"{:.1}\" y1=\"{:.1}\" x2=\"{:.1}\" y2=\"{:.1}\" />\n",
            x1, y1, x2, y2
        ));

        if !wire.net.is_empty() {
            let mx = (x1 + x2) / 2.0;
            let my = (y1 + y2) / 2.0 - 8.0;
            svg.push_str(&format!(
                "<text class=\"net-label\" x=\"{:.1}\" y=\"{:.1}\" text-anchor=\"middle\">{}</text>\n",
                mx, my, escape_xml(&wire.net)
            ));
        }
    }

    // Draw components.
    for comp in &schematic.components {
        let cx = comp.position.x + offset_x;
        let cy = comp.position.y + offset_y;
        let half_w = comp_w / 2.0;
        let half_h = comp_h / 2.0;

        // Body rectangle.
        svg.push_str(&format!(
            "<rect class=\"comp-body\" x=\"{:.1}\" y=\"{:.1}\" width=\"{:.1}\" height=\"{:.1}\" rx=\"3\" />\n",
            cx - half_w, cy - half_h, comp_w, comp_h
        ));

        // Designator.
        svg.push_str(&format!(
            "<text class=\"desig-text\" x=\"{:.1}\" y=\"{:.1}\" text-anchor=\"middle\">{}</text>\n",
            cx, cy - half_h - 4.0, escape_xml(&comp.designator)
        ));

        // Value.
        svg.push_str(&format!(
            "<text class=\"comp-text\" x=\"{:.1}\" y=\"{:.1}\" text-anchor=\"middle\" dominant-baseline=\"central\">{}</text>\n",
            cx, cy, escape_xml(&comp.value)
        ));

        // Footprint.
        if !comp.footprint.is_empty() {
            svg.push_str(&format!(
                "<text class=\"comp-text\" x=\"{:.1}\" y=\"{:.1}\" text-anchor=\"middle\" font-size=\"8\" fill=\"#5a5a64\">{}</text>\n",
                cx, cy + half_h + 12.0, escape_xml(&comp.footprint)
            ));
        }

        // Pins.
        let rot_rad = comp.rotation.to_radians();
        let cos_r = rot_rad.cos();
        let sin_r = rot_rad.sin();

        for pin in &comp.pins {
            let raw_ox = pin.offset.x * grid_step;
            let raw_oy = pin.offset.y * grid_step;
            let rot_ox = raw_ox * cos_r - raw_oy * sin_r;
            let rot_oy = raw_ox * sin_r + raw_oy * cos_r;

            let px = cx + rot_ox;
            let py = cy + rot_oy;

            let pin_color = pin_direction_svg_color(pin.direction);

            // Pin line from body edge.
            let edge_x = if rot_ox < 0.0 {
                cx - half_w
            } else {
                cx + half_w
            };
            let edge_y = cy + rot_oy;

            svg.push_str(&format!(
                "<line class=\"pin-line\" x1=\"{:.1}\" y1=\"{:.1}\" x2=\"{:.1}\" y2=\"{:.1}\" stroke=\"{}\" />\n",
                edge_x, edge_y, px, py, pin_color
            ));

            // Pin dot.
            svg.push_str(&format!(
                "<circle class=\"pin\" cx=\"{:.1}\" cy=\"{:.1}\" fill=\"{}\" />\n",
                px, py, pin_color
            ));
        }
    }

    svg.push_str("</svg>\n");

    ExportResult {
        format: ExportFormat::Svg,
        content: svg,
        extension: "svg".to_string(),
    }
}

/// Calculate bounding box of all components and wires.
fn calculate_bounds(
    schematic: &Schematic,
    grid_step: f32,
    comp_w: f32,
    _comp_h: f32,
) -> (f32, f32, f32, f32) {
    let mut min_x = f32::MAX;
    let mut min_y = f32::MAX;
    let mut max_x = f32::MIN;
    let mut max_y = f32::MIN;

    for comp in &schematic.components {
        let half_w = comp_w / 2.0 + grid_step;
        min_x = min_x.min(comp.position.x - half_w);
        min_y = min_y.min(comp.position.y - half_w);
        max_x = max_x.max(comp.position.x + half_w);
        max_y = max_y.max(comp.position.y + half_w);
    }

    for wire in &schematic.wires {
        min_x = min_x.min(wire.start.x.min(wire.end.x));
        min_y = min_y.min(wire.start.y.min(wire.end.y));
        max_x = max_x.max(wire.start.x.max(wire.end.x));
        max_y = max_y.max(wire.start.y.max(wire.end.y));
    }

    if min_x > max_x {
        (0.0, 0.0, 200.0, 200.0)
    } else {
        (min_x, min_y, max_x, max_y)
    }
}

/// Escape special XML characters.
fn escape_xml(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// SVG color string for pin directions.
fn pin_direction_svg_color(dir: crate::component::PinDirection) -> &'static str {
    use crate::component::PinDirection;
    match dir {
        PinDirection::Input => "#64b4ff",
        PinDirection::Output => "#ff8c3c",
        PinDirection::Bidirectional => "#96dc96",
        PinDirection::Power => "#ff5050",
        PinDirection::Ground => "#787882",
    }
}

// ---------------------------------------------------------------------------
// Gerber export (structural placeholder - needs PCB 3D view)
// ---------------------------------------------------------------------------

/// Manufacturer target for Gerber export.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GerberTarget {
    Jlcpcb,
    PcbWay,
}

impl GerberTarget {
    /// Human-readable name.
    pub fn display_name(&self) -> &str {
        match self {
            Self::Jlcpcb => "JLCPCB",
            Self::PcbWay => "PCBWay",
        }
    }

    /// Required file extensions per manufacturer.
    pub fn required_layers(&self) -> &[&str] {
        match self {
            Self::Jlcpcb => &[
                ".GTL",  // Top copper
                ".GBL",  // Bottom copper
                ".GTS",  // Top soldermask
                ".GBS",  // Bottom soldermask
                ".GTO",  // Top silkscreen
                ".GBO",  // Bottom silkscreen
                ".GKO",  // Board outline
                ".DRL",  // Drill file
            ],
            Self::PcbWay => &[
                ".GTL",
                ".GBL",
                ".GTS",
                ".GBS",
                ".GTO",
                ".GBO",
                ".GML",  // PCBWay uses .GML for outline
                ".DRL",
            ],
        }
    }
}

/// Export result for Gerber (placeholder).
///
/// To generate actual Gerber files, the PCB 3D layout view must
/// be implemented first. This function generates a stub file list
/// showing what will be produced.
pub fn export_gerber_stub(schematic: &Schematic, target: GerberTarget) -> ExportResult {
    let format = match target {
        GerberTarget::Jlcpcb => ExportFormat::GerberJlcpcb,
        GerberTarget::PcbWay => ExportFormat::GerberPcbWay,
    };

    let mut content = String::new();
    content.push_str(&format!(
        "* Gerber export for {} - AuraRafi\n",
        target.display_name()
    ));
    content.push_str(&format!("* Schematic: {}\n", schematic.name));
    content.push_str(&format!("* Components: {}\n", schematic.components.len()));
    content.push_str("*\n");
    content.push_str("* STATUS: PLACEHOLDER - PCB 3D layout view required\n");
    content.push_str("*\n");
    content.push_str("* Files that will be generated:\n");
    for layer in target.required_layers() {
        content.push_str(&format!("*   {}{} - pending\n", schematic.name, layer));
    }
    content.push_str("*\n");
    content.push_str("* To complete Gerber export:\n");
    content.push_str("*   1. Create PCB layout from schematic\n");
    content.push_str("*   2. Place components on board\n");
    content.push_str("*   3. Route traces\n");
    content.push_str("*   4. Run DRC\n");
    content.push_str("*   5. Export Gerber\n");

    ExportResult {
        format,
        content,
        extension: "txt".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Circuit sharing
// ---------------------------------------------------------------------------

/// Serialize a schematic to a shareable compact string.
///
/// The format is RON (human-readable) which can be embedded in
/// a URL or saved as a small file. For browser/WASM targets,
/// this string can be base64-encoded into a URL parameter.
pub fn share_circuit(schematic: &Schematic) -> Result<String, String> {
    ron::ser::to_string(schematic)
        .map_err(|e| format!("Failed to serialize schematic: {}", e))
}

/// Deserialize a schematic from a shared string.
pub fn load_shared_circuit(data: &str) -> Result<Schematic, String> {
    ron::from_str(data)
        .map_err(|e| format!("Failed to deserialize schematic: {}", e))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schematic::Schematic;
    use glam::Vec2;

    fn sample_schematic() -> Schematic {
        let mut sch = Schematic::new("TestCircuit");
        let mut r = ElectronicComponent::resistor("10k");
        r.position = Vec2::new(100.0, 100.0);
        sch.add_component(r);

        let mut led = ElectronicComponent::led();
        led.position = Vec2::new(200.0, 100.0);
        sch.add_component(led);

        sch.add_wire(Vec2::new(120.0, 100.0), Vec2::new(180.0, 100.0), "N1");
        sch
    }

    #[test]
    fn netlist_text_export() {
        let sch = sample_schematic();
        let result = export_netlist_text(&sch);
        assert_eq!(result.extension, "net");
        assert!(result.content.contains("R1"));
        assert!(result.content.contains("D1"));
        assert!(result.content.contains(".COMPONENTS"));
        assert!(result.content.contains(".NETS"));
        assert!(result.content.contains(".END"));
    }

    #[test]
    fn bom_csv_export() {
        let sch = sample_schematic();
        let result = export_bom_csv(&sch);
        assert_eq!(result.extension, "csv");
        assert!(result.content.contains("Designator,Value,Footprint"));
        assert!(result.content.contains("10k"));
        assert!(result.content.contains("LED"));
    }

    #[test]
    fn svg_export() {
        let sch = sample_schematic();
        let result = export_svg(&sch);
        assert_eq!(result.extension, "svg");
        assert!(result.content.contains("<svg"));
        assert!(result.content.contains("</svg>"));
        assert!(result.content.contains("R1"));
    }

    #[test]
    fn empty_schematic_exports() {
        let sch = Schematic::new("Empty");
        let nl = export_netlist_text(&sch);
        assert!(nl.content.contains("Components: 0"));
        let bom = export_bom_csv(&sch);
        assert!(bom.content.contains("Designator"));
        let svg = export_svg(&sch);
        assert!(svg.content.contains("<svg"));
    }
}
