//! AI asset generation interface.
//!
//! Defines traits and data types for AI-generated content:
//! - Mesh generation (3D models from text prompts)
//! - Texture generation (images for materials)
//! - Environment generation (terrain chunks, buildings)
//!
//! **Status**: Traits and types prepared. No AI model connected yet.
//! When ready, implement the traits for specific providers (Stable Diffusion,
//! Point-E, etc.) and wire them into the asset browser panel.
//! See ROADMAP.md for the AI integration milestone.
//!
//! Design: all generation is async (returns a "pending" handle).
//! The engine never blocks waiting for AI output.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Generated asset types
// ---------------------------------------------------------------------------

/// A mesh generated by AI (vertices + faces, ready for EditableMesh).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedMesh {
    /// Flat vertex positions [x, y, z, x, y, z, ...].
    pub positions: Vec<f32>,
    /// Triangle indices (groups of 3).
    pub indices: Vec<u32>,
    /// Optional per-vertex normals [nx, ny, nz, ...].
    pub normals: Vec<f32>,
    /// Source prompt that generated this mesh.
    pub prompt: String,
    /// Generation timestamp.
    pub timestamp: u64,
}

impl GeneratedMesh {
    /// Number of vertices.
    pub fn vertex_count(&self) -> usize {
        self.positions.len() / 3
    }

    /// Number of triangles.
    pub fn triangle_count(&self) -> usize {
        self.indices.len() / 3
    }

    /// Estimated memory usage in bytes.
    pub fn mem_bytes(&self) -> usize {
        self.positions.len() * 4 + self.indices.len() * 4 + self.normals.len() * 4
    }
}

/// A texture generated by AI (raw RGBA pixels).
#[derive(Debug, Clone)]
pub struct GeneratedTexture {
    /// RGBA pixel data.
    pub pixels: Vec<u8>,
    /// Width in pixels.
    pub width: u32,
    /// Height in pixels.
    pub height: u32,
    /// Source prompt.
    pub prompt: String,
}

impl GeneratedTexture {
    /// Estimated memory usage in bytes.
    pub fn mem_bytes(&self) -> usize {
        self.pixels.len()
    }
}

// ---------------------------------------------------------------------------
// Generation request
// ---------------------------------------------------------------------------

/// What type of asset to generate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AssetGenRequest {
    /// Generate a 3D mesh from a text prompt.
    Mesh {
        prompt: String,
        /// Max polygon count (keeps AI output lightweight).
        max_polygons: usize,
    },

    /// Generate a texture from a text prompt.
    Texture {
        prompt: String,
        /// Resolution (width = height for square textures).
        resolution: u32,
    },

    /// Generate a terrain chunk.
    Terrain {
        prompt: String,
        /// Size in world units.
        size: f32,
        /// Resolution (vertices per side).
        resolution: u32,
    },
}

/// Status of an asset generation request.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetGenStatus {
    /// Request queued, waiting for AI.
    Pending,
    /// AI is processing.
    Generating,
    /// Generation complete, result available.
    Ready,
    /// Generation failed with error message.
    Failed(String),
    /// Generation cancelled by user.
    Cancelled,
}

/// A handle to a pending asset generation.
/// The UI polls this to check if the asset is ready.
#[derive(Debug, Clone)]
pub struct AssetGenHandle {
    /// Unique request ID.
    pub id: u64,
    /// What was requested.
    pub request: AssetGenRequest,
    /// Current status.
    pub status: AssetGenStatus,
    /// Generated mesh result (if ready and type is Mesh).
    pub mesh_result: Option<GeneratedMesh>,
    /// Generated texture result (if ready and type is Texture).
    pub texture_result: Option<GeneratedTexture>,
}

// ---------------------------------------------------------------------------
// Generator config
// ---------------------------------------------------------------------------

/// Configuration for AI asset generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssetGenConfig {
    /// Whether AI generation is enabled.
    pub enabled: bool,
    /// Maximum concurrent generation requests.
    pub max_concurrent: usize,
    /// Default max polygon count for meshes.
    pub default_max_polygons: usize,
    /// Default texture resolution.
    pub default_texture_resolution: u32,
    /// Cache generated assets to disk (avoids re-generating).
    pub cache_enabled: bool,
    /// Maximum cache size in MB.
    pub max_cache_mb: usize,
}

impl Default for AssetGenConfig {
    fn default() -> Self {
        Self {
            enabled: false, // Off by default - user must opt in
            max_concurrent: 2,
            default_max_polygons: 500, // Low poly for lightweight engine
            default_texture_resolution: 256, // Small textures
            cache_enabled: true,
            max_cache_mb: 50, // Max 50MB cache
        }
    }
}

/// Lightweight in-memory cache for generated assets.
/// Prevents re-generating the same prompt.
#[derive(Debug, Clone, Default)]
pub struct AssetGenCache {
    /// Cached meshes: (prompt_hash, GeneratedMesh).
    pub meshes: Vec<(u64, GeneratedMesh)>,
    /// Total memory used by cache (bytes).
    pub total_bytes: usize,
    /// Max bytes before eviction.
    pub max_bytes: usize,
}

impl AssetGenCache {
    pub fn new(max_mb: usize) -> Self {
        Self {
            meshes: Vec::new(),
            total_bytes: 0,
            max_bytes: max_mb * 1024 * 1024,
        }
    }

    /// Simple hash of a prompt string (for cache lookup).
    pub fn hash_prompt(prompt: &str) -> u64 {
        let mut hash: u64 = 5381;
        for byte in prompt.bytes() {
            hash = hash.wrapping_mul(33).wrapping_add(byte as u64);
        }
        hash
    }

    /// Look up a cached mesh by prompt.
    pub fn get_mesh(&self, prompt: &str) -> Option<&GeneratedMesh> {
        let hash = Self::hash_prompt(prompt);
        self.meshes.iter()
            .find(|(h, _)| *h == hash)
            .map(|(_, m)| m)
    }

    /// Cache a generated mesh. Evicts oldest if over budget.
    pub fn put_mesh(&mut self, prompt: &str, mesh: GeneratedMesh) {
        let hash = Self::hash_prompt(prompt);
        let bytes = mesh.mem_bytes();

        // Evict oldest entries if over budget.
        while self.total_bytes + bytes > self.max_bytes && !self.meshes.is_empty() {
            let removed = self.meshes.remove(0);
            self.total_bytes = self.total_bytes.saturating_sub(removed.1.mem_bytes());
        }

        self.total_bytes += bytes;
        self.meshes.push((hash, mesh));
    }

    /// Number of cached entries.
    pub fn len(&self) -> usize {
        self.meshes.len()
    }

    /// Is cache empty.
    pub fn is_empty(&self) -> bool {
        self.meshes.is_empty()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_defaults() {
        let config = AssetGenConfig::default();
        assert!(!config.enabled);
        assert_eq!(config.default_max_polygons, 500);
    }

    #[test]
    fn cache_put_get() {
        let mut cache = AssetGenCache::new(10); // 10MB
        let mesh = GeneratedMesh {
            positions: vec![0.0; 9],
            indices: vec![0, 1, 2],
            normals: vec![],
            prompt: "a cube".into(),
            timestamp: 0,
        };
        cache.put_mesh("a cube", mesh);
        assert_eq!(cache.len(), 1);
        assert!(cache.get_mesh("a cube").is_some());
        assert!(cache.get_mesh("a sphere").is_none());
    }

    #[test]
    fn cache_eviction() {
        let mut cache = AssetGenCache::new(0); // 0 MB = always evict
        cache.max_bytes = 100; // 100 bytes max
        let mesh = GeneratedMesh {
            positions: vec![0.0; 30], // 120 bytes
            indices: vec![0; 30],
            normals: vec![],
            prompt: "big".into(),
            timestamp: 0,
        };
        cache.put_mesh("first", mesh.clone());
        cache.put_mesh("second", mesh);
        // First should have been evicted.
        assert!(cache.get_mesh("first").is_none());
    }
}
